# Generated by Django 3.0.8 on 2020-07-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200726_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
