# Generated by Django 3.0.8 on 2020-07-29 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 10, 20, 27, 322946, tzinfo=utc)),
        ),
    ]
