# Generated by Django 3.0.8 on 2020-07-29 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200729_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 15, 51, 49, 505313)),
        ),
    ]
