# Generated by Django 3.0.8 on 2020-07-29 10:30

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200729_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.DateField(default=shop.models.fourteen_days_hence),
        ),
    ]
