# Generated by Django 3.0.8 on 2020-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avl',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
