# Generated by Django 3.0.8 on 2020-07-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_avl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avl',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
