# Generated by Django 3.0.8 on 2020-07-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200730_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avl',
        ),
    ]
