# Generated by Django 3.0.8 on 2020-08-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_product_avl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Sale',
        ),
    ]
