# Generated by Django 3.0.8 on 2020-08-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200813_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Inventory',
        ),
    ]
