# Generated by Django 3.0.8 on 2020-08-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_sale_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='qty',
            field=models.IntegerField(default=10),
        ),
    ]
