# Generated by Django 3.0.8 on 2020-08-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_sale_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='total_cost',
        ),
    ]
